require 'devise'
require 'liquid'
require 'carrierwave-aws'
require 'mongoid'
require 'carrierwave/mongoid'
require 'mongoid_rails_migrations'
require 'delayed_job_mongoid'
# require 'adminlte-rails'
require 'coffee-rails'
require 'font-awesome-rails'
require 'fullcalendar-rails'
require 'icheck-rails'
require 'ionicons-rails'
require 'jquery-rails'
require 'jquery-ui-rails'
require 'jquery-datatables-rails'
require 'jquery-fileupload-rails'
require 'jquery-turbolinks'
require 'less-rails-bootstrap'
require 'momentjs-rails'
require 'redcarpet'
require 'sass-rails'
require 'slim-rails'
require 'turbolinks'
require "canteen/engine"

module Canteen
end
